### ISSUE TITLE
KeyError distance

### ISSUE THREAD

**Issue by JhnTlnd** [matthiasweiss/runtastic-strava-migrate#1]
Hi,

Thanks a lot for the job !
I have an issue during migration activities. 

--------------------------------------------
Importing Run from 2013-03-23T14:34:20
Traceback (most recent call last):
  File "./migrate.py", line 80, in <module>
    import_activity(activity)
  File "./migrate.py", line 59, in import_activity
    "distance": int(activity['distance'])
KeyError: 'distance'

Do I have to change the JSON files ?

Thanks a lot

**Comment by quentindavid** [comment]
Same here !

**Comment by quentindavid** [comment]
@JhnTlnd I tried to use this version and it works:
https://github.com/hci2/runtastic-strava-migrate/blob/feature/add_track_metrics_to_description/migrate.py

There is a pull request, just needs to be accepted :)

**Comment by matthiasweiss** [comment]
Hi, I've just accepted the PR but I actually do not know what the problem is about 😄 
This was a university project of mine that I didn't even know was publicly available 

I hope merging the PR fixes the issue :)
