### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BlanQwall** [matthiasweiss/runtastic-strava-migrate#8]
Hi, Thank you for the instructions. It worked quite fine till I run the last line `./docker_migrate.sh access_token`. Then it take about 10s run the codes and stopped. `docker scout quickview` gives the following: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10673febc]

goroutine 1 [running]:
github.com/docker/scout-cli-plugin/internal/commands/quickview.NewCmd.func2(0x0?, {0x0?, 0x0?, 0x5bc6df9700000000?})
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/internal/commands/quickview/quickview.go:171 +0x63c
github.com/docker/cli/cli-plugins/plugin.RunPlugin.func1.1.2(0x14000aaa908, {0x108becc00, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/docker/cli@v26.1.3+incompatible/cli-plugins/plugin/plugin.go:69 +0x68
github.com/spf13/cobra.(*Command).execute(0x14000aaa908, {0x14000813790, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000acf508)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x14000872500, 0x140002f7808, {{0x10675ecc2, 0x5}, {0x10678897f, 0xb}, {0x14000658966, 0x6}, {0x1067959b9, 0xc}, ...})
	/home/runner/go/pkg/mod/github.com/docker/cli@v26.1.3+incompatible/cli-plugins/plugin/plugin.go:84 +0x138
main.runPlugin(0x14000872500)
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/cmd/docker-scout/main.go:29 +0x104
main.main()
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/cmd/docker-scout/main.go:53 +0x130

I'm not so familar with Docker so I cannot figure out what's happened here. Thanks for help.

**Comment by matthiasweiss** [comment]
Sorry, I'm not really maintaining this anymore

There were multiple PRs and I do not really know what has been modified, so I have to close this...
